const GET_USER_BY_EMAIL = "GET_USER_BY_EMAIL";
const USER_LOGIN_HAS_ERROR = "USER_LOGIN_HAS_ERROR";
const USER_LOGIN_ERROR_MESSAGE = "USER_LOGIN_ERROR_MESSAGE";
const GET_ALL_USER_ROLES = "GET_ALL_USER_ROLES";
const ADD_USER = "ADD_USER";
const ADD_USER_HAS_ERROR = "ADD_USER_HAS_ERROR";
const ADD_USER_ERROR_MESSAGE = "ADD_USER_ERROR_MESSAGE";
const GET_LANGUAGE = "GET_LANGUAGE";
const GET_LANGUAGES = "GET_LANGUAGES";
const GET_DEFAULT_LANGUAGE = "GET_DEFAULT_LANGUAGE";
const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
const GET_ROUTES = "GET_ROUTES";
const GET_FILTERED_ROUTES = "GET_FILTERED_ROUTES";
const UPDATE_ROUTES = "UPDATE_ROUTES";
const DYNAMIC_COMPONENT_TOGGLE = "DYNAMIC_COMPONENT_TOGGLE";
const GET_CONFIG = "GET_CONFIG";
const GET_LOCATIONS = "GET_LOCATIONS";
const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
const UPDATE_CURRENT_LOCATION = "UPDATE_CURRENT_LOCATION";

export {
	GET_USER_BY_EMAIL,
	USER_LOGIN_HAS_ERROR,
	USER_LOGIN_ERROR_MESSAGE,
	GET_ALL_USER_ROLES,
	ADD_USER,
	ADD_USER_HAS_ERROR,
	ADD_USER_ERROR_MESSAGE,
	GET_LANGUAGE,
	GET_LANGUAGES,
	GET_DEFAULT_LANGUAGE,
	UPDATE_LANGUAGE,
	GET_ROUTES,
	GET_FILTERED_ROUTES,
	UPDATE_ROUTES,
	DYNAMIC_COMPONENT_TOGGLE,
	GET_CONFIG,
	GET_LOCATIONS,
	GET_CURRENT_LOCATION,
	UPDATE_CURRENT_LOCATION
};
